version: "3"

services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: trippy
      MYSQL_USER: trippy
      MYSQL_PASSWORD: drosIFMK3LFLdJb1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  node:
    image: node:16
    container_name: node
    command: bash -c "yarn install && yarn dev"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/trippy_api
    working_dir: /trippy_api
    depends_on:
      - db

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
